CREATE TABLE IF NOT EXISTS level_events
(
    lev_ev_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lev_ev_level VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS statuses_events
(
    st_ev_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    st_ev_status VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS roles
(
    rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_role VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS users
(
    us_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    us_telegram_id BIGINT NOT NULL,
    us_name VARCHAR(30) NOT NULL,
    us_role_id BIGINT NOT NULL,
    us_use_date TIMESTAMP,
    CONSTRAINT fk_role_id FOREIGN KEY (us_role_id) REFERENCES roles (rol_id)
);

CREATE TABLE IF NOT EXISTS events
(
    ev_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ev_owner_id BIGINT NOT NULL,
    ev_data_event TIMESTAMP NOT NULL,
    ev_level_event_id BIGINT NOT NULL,
    ev_status_event_id BIGINT NOT NULL,
    ev_description VARCHAR(10000),
    CONSTRAINT fk_ev_level_event_id FOREIGN KEY (ev_level_event_id) REFERENCES level_events (lev_ev_id),
    CONSTRAINT fk_ev_status_event_id FOREIGN KEY (ev_status_event_id) REFERENCES statuses_events (st_ev_id),
    CONSTRAINT fk_ev_owner_id FOREIGN KEY (ev_owner_id) REFERENCES users (us_id)
);

CREATE TABLE IF NOT EXISTS kurses
(
    kur_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kur_number_kurs BIGINT
);

CREATE TABLE IF NOT EXISTS statuses_people
(
    st_pep_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    st_pep_status VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS people
(
    pep_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pep_last_name VARCHAR(40) NOT NULL,
    pep_name VARCHAR(40) NOT NULL,
    pep_patronymic VARCHAR(40) NOT NULL,
    pep_status_people_id BIGINT NOT NULL,
    pep_kurs_id BIGINT NOT NULL,
    CONSTRAINT fk_pep_kurs_id FOREIGN KEY (pep_kurs_id) REFERENCES kurses (kur_id),
    CONSTRAINT fk_pep_status_people_id FOREIGN KEY (pep_status_people_id) REFERENCES statuses_people (st_pep_id)
);

CREATE TABLE IF NOT EXISTS events_people
(
    ev_pep_event_id BIGINT NOT NULL,
    ev_pep_people_id BIGINT NOT NULL,
    PRIMARY KEY (ev_pep_event_id, ev_pep_people_id),
    CONSTRAINT fk_ev_pep_event_id FOREIGN KEY (ev_pep_event_id) REFERENCES events (ev_id),
    CONSTRAINT fk_ev_pep_people_id FOREIGN KEY (ev_pep_people_id) REFERENCES people (pep_id)
);
